# Configuration for this pipeline configuration
type: dev
plugin_id: basic.unreal

# Name to be shown in ShotGrid Desktop
display_name: "test_config_jh_ver1"

# The path to the pipeline configuration
path: "C:/shotgrid_config/tk-config-unreal_ww"
